version: 2.1
orbs:
  docker: circleci/docker@1.5.0

jobs:
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Build front-end
          command: |
            # Your code here
            #echo `pwd`
            ls -lart
            
workflows:
  default:
    jobs:
     - test:
