version: 2.1
orbs:
  docker: circleci/docker@1.5.0

jobs:
  test:
    steps:
      - run:
          name: test
          command: |
            echo "TEST"
            
workflows:
  default:
    jobs:
     - test:
