version: 2.1
orbs:
  docker: circleci/docker@1.5.0
  # Steps
    steps:
      - run:
          name: TEST
          # Add when this will run
          command: |
            echo "TEST"
workflows:
  default:
    jobs:
     - TEST:
      
