  
version: 2.1
orbs:
  docker: circleci/docker@1.5.0

jobs:
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Build front-end
          command: ls -lart
            
workflows:
  default:
    jobs:
     - docker/hadolint:
        dockerfiles: ./Dockerfile
        ignore-rules: 'DL4005,DL3008'
     - docker/publish:
        requires: [docker/hadolint]
        image: krajeevs/udacityp05_v1
        tag: latest 
